# zz-live-ssh.sh — live installer SSH banner, sourced for login shells.
#
# Only the live user gets it (a root SSH session already got in, so re-printing
# the password there buys nothing). Waits briefly for live-ssh-setup.service,
# then prints every interface address plus the autogenerated root password.

if [ "$(id -un 2>/dev/null)" = "user" ]; then
  _live_pw_file="/run/live-ssh/root-pw"
  _live_wait=0
  while [ ! -s "$_live_pw_file" ] && [ "$_live_wait" -lt 10 ]; do
    sleep 1
    _live_wait=$((_live_wait + 1))
  done
  if [ -s "$_live_pw_file" ]; then
    echo
    echo "=== SSH access to this installer ==="
    if command -v ip > /dev/null 2>&1; then
      # shellcheck disable=SC2016
      ip -o -4 addr show scope global 2>/dev/null | awk '{print "  " $2 ": " $4}' || true
    fi
    if command -v hostname > /dev/null 2>&1; then
      echo "  all addresses: $(hostname -I 2>/dev/null || echo none)"
    fi
    echo "  login:    ssh root@<one of the addresses above>"
    echo "  password: $(cat "$_live_pw_file")  (autogenerated, valid until reboot)"
    echo
  fi
  unset _live_pw_file _live_wait
fi
